# Generated by Django 2.2.4 on 2024-05-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0004_auto_20200202_0241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intentos',
        ),
    ]
