# Generated by Django 2.2.4 on 2024-06-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0006_auto_20240616_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion_transito',
            name='NumeroInfraccion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
