# Generated by Django 2.2.4 on 2024-06-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0009_auto_20240616_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos_coip',
            name='Inciso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
