# Generated by Django 2.2.4 on 2024-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0010_auto_20240620_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos_coip',
            name='Articulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
