# Generated by Django 2.2.4 on 2024-07-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0012_auto_20240707_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CedulaAgente',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CodigoAgente',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='ContadorAgente',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='infraccion_transito',
            name='Latitud',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='infraccion_transito',
            name='Longitud',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
