# Generated by Django 2.2.4 on 2024-07-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0013_auto_20240710_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CedulaAgente',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CodigoAgente',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='ContadorAgente',
            field=models.CharField(max_length=1000000),
        ),
    ]
