# Generated by Django 2.2.4 on 2024-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0014_auto_20240710_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CedulaAgente',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CodigoAgente',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='ContadorAgente',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
