# Generated by Django 2.2.4 on 2024-07-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0015_auto_20240710_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CedulaAgente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='CodigoAgente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contadorinfraccion',
            name='ContadorAgente',
            field=models.IntegerField(),
        ),
    ]
