# Generated by Django 2.2.4 on 2024-05-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Informacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='Puntos',
        ),
    ]
