# Generated by Django 2.2.4 on 2024-06-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Informacion', '0005_auto_20240510_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='Apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='CedulaC',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='Nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='Placa',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
