# Generated by Django 2.2.4 on 2024-05-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Usuarios', '0003_auto_20200207_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Juez',
        ),
    ]
