# Generated by Django 2.2.4 on 2024-06-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Usuarios', '0004_delete_juez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente_transito',
            name='Cedula',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agente_transito',
            name='Codigo_Agente',
            field=models.CharField(max_length=1000),
        ),
    ]
