# Generated by Django 2.2.4 on 2024-06-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Usuarios', '0005_auto_20240616_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumeroInfraccion',
        ),
    ]
