# Generated by Django 2.2.4 on 2024-06-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Usuarios', '0006_delete_numeroinfraccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
